export const SIMULATION_CONFIG = {
  ADD_NODES_TOTAL: 500,
  SIMULATE_MOVES_INITIAL_NODES: 200,
  SIMULATE_MOVES_TOTAL: 400,
  SIMULATE_CONNECTIONS_TOTAL: 300,
  STRESS_TEST_NODES: 400,
  STRESS_TEST_INTERACTIONS: 300,
  PROGRESS_CHECK_INTERVAL: 300,
  STRESS_SCREENSHOT_INTERVAL: 100,
};
